#!/bin/sh
bootddev=$(sed -n \
    's#.*root=\(/dev/mmcblk[0-9][0-9]*\)p[0-9][^ ]*.*#\1#p' \
    /proc/cmdline)

mount ${bootddev}p1 /boot
modprobe vvcam_isp
modprobe vvcam_mipi
modprobe vvcam_vb
modprobe vvcam_isp_subdev
modprobe vvcam_video
ISP_MEDIA_SENSOR_DRIVER=/usr/lib/libvvcam.so /usr/bin/isp_media_server > /dev/null 2> /tmp/isp.err.log &

cat /etc/version/release_version

vo_init &
